#include<iostream>
using namespace std;
main()
{
   cout << "Nmuber 1: ";
   float no1;
   cin >> no1;
   cout << "Number 2: ";
   float no2;
   cin >> no2;
   cout << "Number 3: ";
   float no3;
   cin >> no3;
   cout << "Number 4: ";
   float no4;
   cin >> no4;
   cout << "Number 5: ";
   float no5;
   cin >> no5;
   cout << "Number 6: ";
   float no6;
   cin >> no6;
   cout << "Number 7: ";
float no7;
   cin >> no7;
   cout << "Number 8: ";
float no8;
   cin >> no8;
   cout << "Number 9: ";
float no9;
   cin >> no9;
   cout << "Number 10: ";
float no10;
   cin >> no10;
   cout << "Number 11: ";
float no11;
   cin >> no11;
   cout << "Number 12: ";
float no12;
   cin >> no12;
   cout << "Number 13: ";
float no13;
   cin >> no13;
   cout << "Number 14: ";
float no14;
   cin >> no14;
   cout << "Number 15: ";
float no15;
   cin >> no15;
   float final;
   final=(no1+no2+no3+no4+no5)+(no6*no7*no8*no9*no10)-(no11-no12-no13-no14-no15);
   cout << "The final result is: "<<final;
}
